### ISSUE TITLE
SPI Slave AVMM interface not match AVMM interface protocol

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#13]
SPI salve AVMM interface looks strange. The waitreq asserted twice. Need to get rid of one of them:

![image](https://user-images.githubusercontent.com/47224718/132628643-8249d911-48b9-4997-8165-ea23b147fed6.png)

**Comment by johna-eximiusdesign** [comment]
You are issuing multiple write sequences for each address, which is why there are multiple waitreq. The correct sequence shoud have the write terminate after once cycle of waitreq is low. Keeping it high initiates a second transaction. Please see the Avalon specification.

Here is a snippet:
![Untitled](https://user-images.githubusercontent.com/87096041/132706008-2e98700c-dc71-4e6e-946c-d2e63a28a3db.jpg)

and the text from the same section. As indicated, the transfer ends at point 7.
![image](https://user-images.githubusercontent.com/87096041/132706134-c08ce216-2642-46c4-9059-3976b891e665.png)

**Comment by xinyang2k** [comment]
The write sequence of AVMM is not issued by testbench. It is issued by your SPI slave IP state machine. When waitrequest go low, spi slave IP should de-assert write and move on to next transaction. Because the write signal keep asserted, make AVMM slave believe there is another write. The logic handle this is from this file at line 424:

![image](https://user-images.githubusercontent.com/47224718/132711376-1e225565-c225-4a7d-b065-5d4b4631449c.png)

Here is the waveform associated with the state machine:
![image](https://user-images.githubusercontent.com/47224718/132711649-6438632d-f555-4d0c-a920-c5cc258ff3d8.png)

**Comment by johna-eximiusdesign** [comment]
Bug confirmed and being worked on.

**Comment by xinyang2k** [comment]
Bug has been fixed from 0.85 check in.
