### ISSUE TITLE
Inquiry of 24 channel programming of AIB with identical csr value

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#17]
User wants to program 24 channels with one set of CSR value. What is the procedure to do that? Can DV describe and try out in your test?

**Comment by johna-eximiusdesign** [comment]
FW can use a for loop to perform the various iterations, which is the typical solution for any repeated sequence like this.

**Comment by xinyang2k** [comment]
This is a default usage case for this IP.  User needs to send 24 set of identical data through SPI bus is not a reasonable usage.

**Comment by johna-eximiusdesign** [comment]
This is how this is done in a variety of SPI IP. Personally I can attest to Synopsys, Cadence, ARM API, NXP, several Korean IPs and probably a half dozen other chips/designs. Generally you do not add hardware for a replay feature because the processor operates at several orders of magnitude higher bandwidth, so the additional hardware provides no system benefit. But in any case, this is not in the accepted HAS and we are not accepting new features at this time.

**Comment by nij-intel** [comment]
Assigning this to Julie for now

**Comment by dkehlet** [comment]
Feature for future consideration.
