### ISSUE TITLE
Need workaround to AIB link ready race condition: expand "X" parameter

### ISSUE THREAD

**Issue by dkehlet** [chipsalliance/aib-protocols#40]
The delay of link ready signals sl_tx_transfer_en and ms_tx_transfer_en through the AIB sideband to the other side causes one side to see link ready (both signals above true) long before the other side.
Workaround concept: add extra delay (or use units of 128 data UI) in the "X" delay input to the AXI4 MM adapter.

**Comment by dkehlet** [comment]
Concept: change parameter X to be 16b, so it can count up to 64K UI.

**Comment by johna-eximiusdesign** [comment]
This is in theory fixed in the latest drop (0.8.16). However, we are adjusting the final recommended values as new corner cases arise in simulation. For example, the Y term which is defined as "Guaranteed time until remote CA is aligned" was originally thought to be primarily affected by inter channel skew. But in sims, we are seeing that a large interval between successive transmission of strobes can make a significant contribution to a delay in CA alignment.

So, we're refining the actual values, but the overall flow is defined and in good shape. Below is the snapshot of the original numbers and a brief writeup of X,Y and Z.

![auto_synchronization](https://user-images.githubusercontent.com/87096041/141044721-96627c50-9b15-4f18-9c37-125baca48dc5.jpg)

We can leave this open until the numbers / documentation is finalized.

**Comment by johna-eximiusdesign** [comment]
This should be in LLINK user guide as of 0.9.1.

**Comment by dkehlet** [comment]
Thanks very much.
