### ISSUE TITLE
directed reset test not toggling tx_online

### ISSUE THREAD

**Issue by nij-intel** [chipsalliance/aib-protocols#82]
![image](https://user-images.githubusercontent.com/90720651/154320440-4176bc7a-0b66-4e16-9dcd-188bd14ef1e8.png)

Top-level tx_online (highlighted above) is not getting de-asserted with reset toggle it is only toggling the signal below in concat block.

1st tx_online: axist_top_tb.axist_DUT_wrapper.axi_st_ll_msr.tx_online
2nd tx_online: axist_top_tb.axist_DUT_wrapper.axi_st_ll_msr.axi_st_master_concat.tx_online

**Comment by nij-intel** [comment]
![image](https://user-images.githubusercontent.com/90720651/154320642-b4e2cac8-0a68-443e-95f8-47a239628775.png)

**Comment by johna-eximiusdesign** [comment]
The yellow oval does not support entering / re-exiting reset, so we don't reset the AIB, which effectively drives the ONLINE signals which is why they stay high. As you noted, we do reset the DUT, which tests the ability for it to enter/exit reset. By doing this, we also test that the logic link layer can operate coming out of reset with the ONLINE immediately high, which provided another corner to test at. For these reasons, we only place the LLINK (and CA) into reset and leave the AIB link up and running.

**Comment by nij-intel** [comment]
use the tx_online delayed version (one below) to look at llink status. Highlighted tx_online does not toggle with LLink reset and will only toggle with AIB channel reset or AIB reset. This should be noted when we are observing tx_online status for AXI4

tx_online delayed version is available on the *_debug_status

**Comment by nij-intel** [comment]
AIB channel reset or AIB reset did not result in a successful AIB link-up after reset toggle this should be debugged further. I will keep this open for this issue.

**Comment by nij-intel** [comment]
This is not an issue, to trigger this we need hard reset of AIB
